// Auto-generated by add_indices.py
import AdminRegion from "./AdminRegion";
import DSD from "./DSD";
import District from "./District";
import GND from "./GND";
import Province from "./Province";

export { AdminRegion, DSD, District, GND, Province };
