// Auto-generated by javascript_version.py
export const DATETIME_STR = "2025-12-02 14:58:50";
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = { DATETIME_STR, VERSION_DATETIME };
export default VERSION;
