// Auto-generated by add_indices.py
import Alert from "./Alert";
import AlertFlood from "./AlertFlood";
import ExtremeHeat from "./ExtremeHeat";
import ExtremeRain from "./ExtremeRain";
import HeavyRain from "./HeavyRain";
import LandslideWarningLevel1 from "./LandslideWarningLevel1";
import LandslideWarningLevel2 from "./LandslideWarningLevel2";
import LandslideWarningLevel3 from "./LandslideWarningLevel3";
import MajorFlood from "./MajorFlood";
import MinorFlood from "./MinorFlood";
import VeryHeavyRain from "./VeryHeavyRain";

export {
  Alert,
  AlertFlood,
  ExtremeHeat,
  ExtremeRain,
  HeavyRain,
  LandslideWarningLevel1,
  LandslideWarningLevel2,
  LandslideWarningLevel3,
  MajorFlood,
  MinorFlood,
  VeryHeavyRain,
};
