// Auto-generated by add_indices.py
import LandslideRegionDetails from "./LandslideRegionDetails";
import LandslideWarningView from "./LandslideWarningView";

export { LandslideRegionDetails, LandslideWarningView };
