// Auto-generated by add_indices.py
import AdminRegionIcon from "./AdminRegionIcon";
import GaugeStationIcon from "./GaugeStationIcon";
import LocationIcon from "./LocationIcon";
import WeatherStationIcon from "./WeatherStationIcon";

export { AdminRegionIcon, GaugeStationIcon, LocationIcon, WeatherStationIcon };
