// Auto-generated by add_indices.py
import AdminRegionIcon from "./AdminRegionIcon";
import GaugingStationIcon from "./GaugingStationIcon";
import LocationIcon from "./LocationIcon";
import RoleIcon from "./RoleIcon";
import WeatherStationIcon from "./WeatherStationIcon";

export {
  AdminRegionIcon,
  GaugingStationIcon,
  LocationIcon,
  RoleIcon,
  WeatherStationIcon,
};
